name: release-please

on:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      release_release_created: ${{ steps.release.outputs.release_created }}
      release_sha: ${{ steps.release.outputs.sha }}
      release_tag_name: ${{ steps.release.outputs.tag_name }}
    env:
      BLENDER_ARCHIVE_URL: https://mirrors.ocf.berkeley.edu/blender/release/Blender4.2/blender-4.2.3-linux-x64.tar.xz
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # これをやるとrelease-please-actionが安定する気がする
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          target-branch: main

  upload-release-archive:
    runs-on: ubuntu-24.04
    needs: release-please
    if: ${{ needs.release-please.outputs.release_release_created }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.release-please.outputs.release_sha }}
      - name: Install package
        run: |
          sudo apt-get update -qq
          sudo apt-get dist-upgrade -y
          sudo apt-get install -y advancecomp blender curl git python3 python3-numpy ruby shellcheck xz-utils
      - name: Cache archive
        id: cache-archive
        uses: actions/cache@v4
        with:
          path: blender.tar.xz
          key: ${{ env.BLENDER_ARCHIVE_URL }}-archive-1
      - name: Download archive
        if: steps.cache-archive.outputs.cache-hit != 'true'
        run: |
          curl --fail --location --show-error --retry 5 --retry-all-errors "$BLENDER_ARCHIVE_URL" -o blender.tar.xz
          test "$(md5sum blender.tar.xz)" = "34fe4456252a703c39cb93efbfa84f8c  blender.tar.xz"
      - name: Release
        run: ./tools/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          RELEASE_TAG_NAME: ${{ needs.release-please.outputs.release_tag_name }}
